
# ======================= 主题美化类 ========================

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'       
on_cmd=['Colors']

[[plugins]]
repo = 'morhetz/gruvbox'                          
on_cmd=['Colors']

[[plugins]]
repo = 'ayu-theme/ayu-vim'                        
on_cmd=['Colors']

[[plugins]]
repo = 'arcticicestudio/nord-vim'                 
on_cmd=['Colors']

[[plugins]]
repo = 'rakr/vim-one'                             
on_cmd=['Colors']

[[plugins]]
repo = 'mhartington/oceanic-next'                 
on_cmd=['Colors']


# ========================== 实用类 ===========================
# 缩进提示
[[plugins]]
repo = 'yggdroot/indentline'

# 快速选择
[[plugins]]
repo = 'terryma/vim-expand-region'
on_map = {n = '<Plug>'}
hook_add ='''
    map <CR> <Plug>(expand_region_expand)
    map _ <Plug>(expand_region_shrink)
'''

# 通用编辑
[[plugins]]
repo = 'mg979/vim-visual-multi'
on_map = {n='<C-n>'}

[[plugins]]
repo = 'jiangmiao/auto-pairs'


[[plugins]]
repo = 'tpope/vim-surround'                       

[[plugins]]
repo = 'mbbill/undotree'                          
on_cmd = ['UndotreeToggle']

[[plugins]]
repo = 'simnalamburt/vim-mundo'                   
on_cmd = ['MundoToggle' ]

# 左边栏显示mark
[[plugins]]
repo = 'kshenoy/vim-signature'

# Docker管理
[[plugins]]
repo = 'kevinhui/vim-docker-tools'                
on_cmd = ['DockerToolsToggle' ]

# 文件管理
[[plugins]]
repo = 'scrooloose/nerdtree'                      
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'francoiscabrol/ranger.vim'                
on_cmd = ['Ranger']

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

# 搜索
[[plugins]]
repo = 'junegunn/fzf'                             
build = "~/.fzf/install --all"
on_path ='.*'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_path ='.*'


[[plugins]]
repo = 'pelodelfuego/vim-swoop'

[[plugins]]
repo = 'dyng/ctrlsf.vim'                          
on_cmd=['CtrlSF']

# 实时显示正则替换
[[plugins]]
repo = 'osyo-manga/vim-over'                      
on_cmd = ['OverCommandLine']

# 给同样的单词加下划线
[[plugins]]
repo = 'itchyny/vim-cursorword'

# 高亮html/xml tags
[[plugins]]
repo = 'Valloric/MatchTagAlways'                  # { 'for':['html','tags']}

# 快速跳转
[[plugins]]
repo = 'easymotion/vim-easymotion'                # {'on': ['<Plug>(easymotion-overwin-f','<Plug>(easymotion-Fn']}

[[plugins]]
repo = 'rhysd/clever-f.vim'

# 对齐格式
[[plugins]]
repo = 'junegunn/vim-easy-align'                  # { 'on': ['<Plug>(EasyAlign)']}

# 方便地移动上下行
[[plugins]]
repo = 'matze/vim-move'                           # { 'on': [ '<Plug>MoveLineDown', '<Plug>MoveLineUp' ]}

# 强大的表格模式
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'               # { 'on': [ 'TableModeToggle', '<Plug>(table-mode-tableize)' ]}

# 方便的调用终端
[[plugins]]
repo = 'wvffle/vimterm'

# 各种实用命令
[[plugins]]
repo = 'tpope/vim-eunuch'

# 输入法切换,内容为中文时，会自动切换，按esc后自动切换成英文
[[plugins]]
repo = 'neoclide/coc-imselect'






# ========================== 代码类 ===========================


# 代码检查和补全
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'w0rp/ale'


# {'do': './install.sh nightly'} # Install nightly build, replace ./install.sh with install.cmd on windows
# curl --fail -L https://install-node.now.sh/latest | sh " install nodejs >=8.0
# curl --compressed -o- -L https://yarnpkg.com/install.sh | bash " Install yarn
# :CocInstall coc-python
# :CocInstall coc-yaml
# :CocInstall coc-html
# :CocInstall coc-tsserver
# :CocInstall coc-css
# :CocInstall coc-java
# :CocInstall coc-ultisnips
# :CocInstall coc-yank
# :CocInstall coc-pairs

# 异步运行
[[plugins]]
repo = 'skywind3000/asyncrun.vim'                 # { 'on': ['AsyncRun','AsyncStop']}

# REPL
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'Chandlercjy/neoterm'                      # {'on':[ 'TREPLSendFile', '<Plug>(neoterm-repl-send)', '<Plug>(neoterm-repl-send-line)' ]}

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Chandlercjy/git-blame.vim'                # { 'on': ['GitBlame']}




[[plugins]]
repo = 'majutsushi/tagbar'                        # {'on':['TagbarToggle']}


# 语言相关
[[plugins]]
repo = 'vhdirk/vim-cmake'                         # { 'for' : ['c','cpp','hpp','h']}

[[plugins]]
repo = 'leafgarland/typescript-vim'               # { 'for' : ['typescript']}
on_cmd = ['typescript']

[[plugins]]
repo = 'fatih/vim-go'                             # { 'for' : ['go'], 'do': ':GoUpdateBinaries'}
on_cmd = ['go']
hook_add ='''
    autocmd Filetype go nnoremap <buffer> <S-Tab> :GoDoc<CR>
'''

# 自动生成ctags和查看
# [[plugins]]
# repo = 'ludovicchabant/vim-gutentags'

# [[plugins]]
# repo = 'skywind3000/gutentags_plus'



# ======================== 系统增强类 =========================
[[plugins]]
repo = 'pseewald/vim-anyfold'                      # 加强缩进折叠

[[plugins]]
repo = 'tpope/vim-repeat'                          # 系统.命令的加强

[[plugins]]
repo = 'pbrisbin/vim-mkdir'                        # 可以自动创建文件夹不报错

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'            # Tmux加强

[[plugins]]
repo = 'tmux-plugins/vim-tmux-focus-events'


# ========================== 趣味类 ===========================

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'            # 舒服的滚动

[[plugins]]
repo = 'tweekmonster/startuptime.vim'             # {'on': ['StartupTime']} # 检查启动时间

[[plugins]]
repo = 'junegunn/goyo.vim'                        # {'on':'Goyo'}           # 无打扰模式


[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'christianrondeau/vim-base64'


[[plugins]]
repo = 'tex/vimpreviewpandoc'

[[plugins]]
repo = 'Chandlercjy/vim-markdown-folding'         # { 'for':'markdown'}     # Markdown插件

[[plugins]]
repo = 'Chandlercjy/vim-markdown-edit-code-block' # { 'for':'markdown'}

[[plugins]]
repo = 'iamcco/markdown-preview.vim'              # { 'for':'markdown'}     # Markdown插件

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'          # { 'for':'markdown'}     # Markdown插件

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'mzlogin/vim-markdown-toc'                 # { 'for':'markdown'}

[[plugins]]
repo = 'plasticboy/vim-markdown'                  # { 'for':'markdown'}


[[plugins]]
repo = 'lvht/tagbar-markdown'                     # { 'for':'markdown'}


[[plugins]]
repo = 'pangloss/vim-javascript'                  # { 'for' : ['javascript']} # 需要测试

# 方便地控制窗口

[[plugins]]
repo = 'romgrk/winteract.vim'                     # {'on': 'InteractiveWindow'}

[[plugins]]
repo = 't9md/vim-choosewin'                       # {'on': ['<Plug>(choosewin)']}

[[plugins]]
repo = 'wellle/visual-split.vim'                  # {'on':['<Plug>(Visual-Split-VSSplitAbove)', '<Plug>(Visual-Split-VSSplitBelow)']}

# PlantUML

[[plugins]]
repo = 'tyru/open-browser.vim'                    # { 'for':'plantuml'}

[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'         # { 'for':'plantuml'}  # 还需要安装 Graphviz 依赖



[[plugins]]
repo = 'scrooloose/nerdcommenter'                 
on_ft =['vim','json','go','html','js','jsx','py','css','less','tmpl','toml','xml','sql']
hook_add = '''
    let g:NERDSpaceDelims = 1
    let g:NERDCreateDefaultMappings = 0
    map ,cc <Plug>NERDCommenterToggle
    map ; <Plug>NERDCommenterToggle
'''

